/*
 * Copyright 2026 Takakiyo Tanaka (IBM Japan)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ibm.jp.automation.e2m.maven;

import com.ibm.jp.automation.e2m.eclipse.EclipseProject;
import com.ibm.jp.automation.e2m.i18n.Messages;
import com.ibm.jp.automation.e2m.util.AppLogger;

import org.slf4j.Logger;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Liberty の server.xml を生成するクラス。
 *
 * <p>プロジェクトの Servlet バージョンから Liberty プラットフォーム feature を決定し、
 * {@code src/main/liberty/config/server.xml} に書き出す。</p>
 *
 * <p>Servlet バージョンと Liberty feature のマッピング:
 * <table>
 *   <tr><th>Servlet</th><th>Liberty feature</th></tr>
 *   <tr><td>3.1</td><td>javaee-7.0</td></tr>
 *   <tr><td>4.0</td><td>javaee-8.0</td></tr>
 *   <tr><td>5.0</td><td>jakartaee-9.1</td></tr>
 *   <tr><td>6.0</td><td>jakartaee-10.0</td></tr>
 *   <tr><td>6.1</td><td>jakartaee-11.0</td></tr>
 *   <tr><td>3.0 以前 / 不明</td><td>javaee-7.0（Liberty 未対応のため）</td></tr>
 * </table>
 * </p>
 */
public class LibertyServerXmlGenerator {

    private static final Logger log = AppLogger.get(LibertyServerXmlGenerator.class);

    /** server.xml 雛形。LIBERTY_FEATURE、ARTIFACT_ID、CONTEXT_ROOT をプレースホルダーとして使用する。 */
    private static final String SERVER_XML_TEMPLATE = """
            <?xml version="1.0" encoding="UTF-8"?>

            <!-- generated by e2m -->
            <server description="Liberty Server">

                <!-- Enable features -->
                <featureManager>
                    <feature>LIBERTY_FEATURE</feature>
                </featureManager>

                <!-- This template enables security. To get the full use of all the capabilities, a keystore and user registry are required. -->

                <!-- For the keystore, default keys are generated and stored in a keystore. To provide the keystore password, generate an 
                    encoded password using bin/securityUtility encode and add it below in the password attribute of the keyStore element. 
                    Then uncomment the keyStore element. -->
                <!--
                <keyStore password=""/> 
                -->

                <!--For a user registry configuration, configure your user registry. For example, configure a basic user registry using the
                    basicRegistry element. Specify your own user name below in the name attribute of the user element. For the password,
                    generate an encoded password using bin/securityUtility encode and add it in the password attribute of the user element.
                    Then uncomment the user element. -->
                <basicRegistry id="basic" realm="BasicRealm">
                    <!--
                    <user name="yourUserName" password="" />
                    -->
                </basicRegistry>

                <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="9080" httpsPort="9443"/>

                <!-- Automatically expand WAR files and EAR files -->
                <applicationManager autoExpand="true"/>

                <!-- Configures the application on a specified context root -->
                <webApplication location="ARTIFACT_ID.war" contextRoot="/CONTEXT_ROOT"/>

                <!-- Default SSL configuration enables trust for default certificates from the Java runtime -->
                <ssl id="defaultSSLConfig" trustDefaultCerts="true" />
            </server>
            """;

    private LibertyServerXmlGenerator() {}

    /**
     * server.xml を生成して {@code outputDir/src/main/liberty/config/server.xml} に保存する。
     *
     * <p>contextRoot の決定順序:
     * <ol>
     *   <li>{@link EclipseProject#webContextRoot()} が非 null の場合はその値を使用</li>
     *   <li>null の場合は artifactId を使用</li>
     * </ol>
     * </p>
     *
     * @param eclipseProject パース済み Eclipse プロジェクト情報
     * @param artifactId     生成する Maven プロジェクトの artifactId
     * @param outputDir      Maven プロジェクトの出力ディレクトリ
     * @throws Exception ファイル書き込みに失敗した場合
     */
    public static void generate(EclipseProject eclipseProject, String artifactId, Path outputDir)
            throws Exception {

        String libertyFeature = resolveLibertyFeature(eclipseProject.webVersion());
        log.debug("  Liberty feature: {}", libertyFeature);

        String contextRoot = eclipseProject.webContextRoot() != null
                ? eclipseProject.webContextRoot()
                : artifactId;
        log.debug("  contextRoot: {}", contextRoot);

        String content = SERVER_XML_TEMPLATE
                .replace("LIBERTY_FEATURE", libertyFeature)
                .replace("ARTIFACT_ID", artifactId)
                .replace("CONTEXT_ROOT", contextRoot);

        Path configDir = outputDir.resolve("src/main/liberty/config");
        Files.createDirectories(configDir);
        Path serverXmlPath = configDir.resolve("server.xml");
        Files.write(serverXmlPath, content.getBytes(StandardCharsets.UTF_8));

        log.info(Messages.get("liberty.serverXmlGenerated", serverXmlPath));
    }

    /**
     * Servlet バージョン文字列から Liberty プラットフォーム feature 名を決定する。
     *
     * @param webVersion Servlet 仕様のバージョン（例: {@code "4.0"}）。null の場合は {@code "javaee-7.0"}
     * @return Liberty feature 名（例: {@code "javaee-8.0"}）
     */
    static String resolveLibertyFeature(String webVersion) {
        if (webVersion == null) {
            return "javaee-7.0";
        }
        return switch (webVersion) {
            case "3.1" -> "javaee-7.0";
            case "4.0" -> "javaee-8.0";
            case "5.0" -> "jakartaee-9.1";
            case "6.0" -> "jakartaee-10.0";
            case "6.1" -> "jakartaee-11.0";
            default    -> "javaee-7.0"; // 3.0 以前または不明
        };
    }
}
